const mongoose = require("mongoose")

const vehicleLocationSchema = new mongoose.Schema({
    displayId:{
        type:String,
        default:''
    },
    companyId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Company'
    },
    driverId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Driver'
    },
    vehicleId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Vehicle'
    },
    status:{
        type:String,
        enum:['STATIONARY','IN_MOTION'],
        default:'STATIONARY'
    },
    inMotionLocations:[{
        eventCode:{
            type:String,
            enum:['PERIODIC','TRIP_START','TRIP_END'],
            default:'PERIODIC'
        },
        periodicType:{
            type:String,
            enum:[1,2,3],
            default:1
            //1 for trip start, 2 for motion, 3 for end
        },
        lat:{
            type:String,
            default:''
        },
        lng:{
            type:String,
            default:''
        },
        state:{
            type:String,
            default:''
        },
        speed:{
            type:String,
            default:''
        },
        heading:{
            type:String,
            default:''
        },
        odometer:{
            type:String,
            default:''
        },
        engineHours:{
            type:String,
            default:''
        },
        fuelLevel:{
            type:String,
            default:''
        },
        eventDate:{
            type:Date
        }
    }],
    stationaryLocations:[{
        eventCode:{
            type:String,
            enum:['BLE_OFF','BLE_ON','ENG_OFF','ENG_ON'],
            default:'BLE_OFF'
        },
        periodicType:{
            type:String,
            enum:[1,2,3],
            default:1
            //1 for trip start, 2 for motion, 3 for end
        },
        lat:{
            type:String,
            default:''
        },
        lng:{
            type:String,
            default:''
        },
        state:{
            type:String,
            default:''
        },
        speed:{
            type:String,
            default:''
        },
        heading:{
            type:String,
            default:''
        },
        odometer:{
            type:String,
            default:''
        },
        engineHours:{
            type:String,
            default:''
        },
        fuelLevel:{
            type:String,
            default:''
        },
        eventDate:{
            type:Date
        }
    }],
    startTime:{
        type:Date
    },
    endTime:{
        type:Date
    },
    eventDate:{
        type:Date
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    updatedBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    createdAt:{
        type:Date,
        default: Date.now
    },
    updatedAt:{
        type:Date,
        default: Date.now
    },
    isActive:{
        type:Boolean,
        default:true
    },
    isDeleted:{
        type:Boolean,
        default:false
    }
})

const VehicleLocation = mongoose.model('VehicleLocation',vehicleLocationSchema)
module.exports = VehicleLocation